Linux:
	gcc JYH_main.c JYH_LE.c JYH_EX.c JYH_MM.c JYH_PL.c JYH_WS.c JYH_LS.c JYH_AUX.c JYH_Object.c JYH_Camera.c JYH_Trans.c -lSDL2 -lSDL2_ttf -lSDL2_image
	
Windows:
	gcc JYH_main.c JYH_Editor.c JYH_LvlRunner.c JYH_Menu.c JYH_PlayerLvlSelection.c JYH_WorldSelection.c JYH_LvlSelection.c JYH_AUX.c -I .\include\  -L .\lib\  -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf -lSDL2_image
